### ISSUE TITLE
Works client side but not server side.

### ISSUE THREAD

**Issue by SuperKittyGamer** [RedstoneWizard08/Permitted#1]
Hello! I attempted to add this mod to a modpack to hopefully have a cool Permit system, unfortunately the mod wont boot when attempting to use it on a server, but boots locally just fine on client side.

https://mclo.gs/HHoW704

Linked above is the servers Crash Log that contains the major details, but I was hoping to see if this is something on my end or a problem with the mod.

**Comment by RedstoneWizard08** [comment]
@SuperKittyGamer thanks for the report! I'll take a look as soon as I can (hopefully within the next day or two).

**Comment by RedstoneWizard08** [comment]
Yeah looks like a problem on my end, the mod is trying to access a class only available on servers. I'll have to do a little digging but it hopefully shouldn't take too long.

**Comment by SuperKittyGamer** [comment]
Tysm!

**Comment by RedstoneWizard08** [comment]
Sorry I haven't been able to get to it yet, homework has been a pain. I'll try to get to it later today.

**Comment by RedstoneWizard08** [comment]
Okay, I've found the issue and fixed it. I'll upload the fix to Modrinth and CurseForge later today (I can't right now). :)

**Comment by RedstoneWizard08** [comment]
I closed the issue, but I'll let you know when the fix is uploaded. I'm also gonna work on CI and multi-loader support (so adding support for Fabric!). :)

**Comment by RedstoneWizard08** [comment]
@SuperKittyGamer it has been published on modrinth! https://modrinth.com/mod/permitted/version/0.2.1

**Comment by SuperKittyGamer** [comment]
Perfect! Thank you so much for the help!
